name: Backend CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: flight_booking_dev # Matches your development database

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Navigate to Backend Directory
      - name: Change Working Directory to Backend
        working-directory: ./backend

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./backend

      # Step 5: Configure Test Environment
      - name: Configure Test Environment
        run: |
          echo "DB_TEST_USER=postgres" >> .env.test
          echo "DB_TEST_PASS=postgres" >> .env.test
          echo "DB_TEST_NAME=flight_booking_dev" >> .env.test
          echo "DB_TEST_HOST=localhost" >> .env.test
        working-directory: ./backend

      # Step 6: Wait for PostgreSQL to be Ready
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done
        env:
          PGPASSWORD: postgres

      # Step 7: Create Test Database
      - name: Create Test Database
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE flight_booking_dev;"
        env:
          PGPASSWORD: postgres

      # Step 8: Run Migrations
      - name: Run Migrations
        run: npx sequelize-cli db:migrate --env test
        working-directory: ./backend

      # Step 9: Run Tests
      - name: Run Tests
        run: npm test
        working-directory: ./backend
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Deployment placeholder (update with your deployment steps)
      - name: Deployment Placeholder
        run: echo "Add deployment steps here"